-- SCRUM-246/247. PostgreSQL: UUID, identity, timestamptz, JSONB y FK a InsForge Auth.
CREATE TABLE public.roles (
  id text PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);
INSERT INTO public.roles VALUES
  ('cliente', 'Cliente'), ('mesera', 'Mesera'), ('cocina', 'Cocina'),
  ('caja', 'Caja'), ('admin', 'Administrador');

CREATE TABLE public.perfiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre text NOT NULL DEFAULT '',
  apellido text NOT NULL DEFAULT '',
  telefono text NOT NULL DEFAULT '' CHECK (telefono = '' OR telefono ~ '^9[0-9]{8}$'),
  rol text NOT NULL DEFAULT 'cliente' REFERENCES public.roles(id),
  activo boolean NOT NULL DEFAULT true,
  preferencias jsonb NOT NULL DEFAULT '{"notificacionesEmail":true,"notificacionesPromos":true}',
  creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.categorias (
  id text PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text NOT NULL DEFAULT '',
  imagen text,
  activo boolean NOT NULL DEFAULT true
);
CREATE TABLE public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id text NOT NULL REFERENCES public.categorias(id),
  nombre text NOT NULL,
  descripcion text NOT NULL DEFAULT '',
  precio numeric(10,2) NOT NULL CHECK (precio >= 0),
  imagen text,
  disponible boolean NOT NULL DEFAULT true
);
CREATE TABLE public.mesas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero text NOT NULL UNIQUE,
  capacidad smallint NOT NULL CHECK (capacidad > 0),
  forma text NOT NULL,
  zona text NOT NULL,
  estado text NOT NULL DEFAULT 'libre' CHECK (estado IN ('libre','ocupada','reservada'))
);
CREATE TABLE public.estados (
  id text PRIMARY KEY,
  nombre text NOT NULL,
  orden smallint NOT NULL UNIQUE
);
INSERT INTO public.estados VALUES
  ('recibido','Recibido',1), ('preparacion','En preparación',2), ('listo','Listo',3),
  ('camino','En camino',4), ('entregado','Entregado',5), ('cancelado','Cancelado',6);
CREATE TABLE public.pedidos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo text NOT NULL UNIQUE,
  cliente_id uuid REFERENCES public.perfiles(id),
  creado_por uuid NOT NULL REFERENCES public.perfiles(id),
  mesa_id bigint REFERENCES public.mesas(id),
  tipo text NOT NULL CHECK (tipo IN ('delivery','recojo','mesa')),
  estado_id text NOT NULL DEFAULT 'recibido' REFERENCES public.estados(id),
  subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0),
  envio numeric(10,2) NOT NULL DEFAULT 0 CHECK (envio >= 0),
  total numeric(10,2) NOT NULL CHECK (total = subtotal + envio),
  direccion jsonb,
  notas text,
  creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.detalles_pedido (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pedido_id uuid NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES public.productos(id),
  nombre_producto text NOT NULL,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario >= 0),
  notas text
);
CREATE TABLE public.pagos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL REFERENCES public.pedidos(id),
  registrado_por uuid NOT NULL REFERENCES public.perfiles(id),
  metodo text NOT NULL CHECK (metodo IN ('efectivo','tarjeta','yape','plin')),
  monto numeric(10,2) NOT NULL CHECK (monto > 0),
  estado text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','confirmado','anulado')),
  referencia text,
  creado_en timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX pedidos_cliente_fecha_idx ON public.pedidos(cliente_id, creado_en DESC);
CREATE INDEX pedidos_estado_idx ON public.pedidos(estado_id);
CREATE INDEX detalles_pedido_id_idx ON public.detalles_pedido(pedido_id);
CREATE INDEX pagos_pedido_id_idx ON public.pagos(pedido_id);

-- Evitar acceso hasta aplicar la migración de políticas.
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalles_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;
